# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Wordoko
tagline:	'Play Wordoko. Learn Japanese.'
description:	'Wordoko site.'
url:		http://wordoko.com

author:
  name:		'Juan Lazo'
  url:		

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/
    desc:	Wordoko on twitter

  - icon:	facebook-alt
    url:	https://github.com/
    desc:	Wordoko on facebook

  - icon:	googleplus-alt
    url:	https://google.com/
    desc:	Wordoko on google+

    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	Wordoko
  url:		http://wordoko.com
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
