# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Wordoko
tagline:	Play Wordoko. Learn Japanese.
description:	 'Wordoko site.'
url:		http://wordoko.com

author:
  name:		'Juan Lazo'
  url:		

paginate:	5o

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/iancamporez
    desc:	Wordoko on Twitter

  - icon:	facebook
    url:	https://facebook.com/camporez
    desc:	Wordoko on Facebook

  - icon:	googleplus-alt
    url:	https://google.com/+IanCamporezBrunelli
    desc:	Wordoko on google+

    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	Juan Lazo
  url:		
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
